### ISSUE TITLE
DisableIfHasHelmet not working bug

### ISSUE THREAD

**Issue by kaxonomy** [xSavior-of-God/ArmorStand-Limiter#4]
I'm using 1.18.2 papermc and the current comparison to determine if armorstands are wearing a helmet doesn't work. I recommend changing it to `armorstand.getEquipment().getHelmet().getType() != Material.AIR` for later versions of mc.

**Comment by kaxonomy** [comment]
Alternatively, I'd prefer if this check instead ignores all armorstands that have an item in any equipment slot.

**Comment by xSavior-of-God** [comment]
Hi @kaxon-dev, 
thanks again for the report... I fixed the problem

https://github.com/xSavior-of-God/ArmorStand-Limiter/blob/e298b2bb4c1140fafc935f313ceaf25bace7f8cb/src/main/java/com/xSavior_of_God/ArmorStandLimiter/Utilis.java#L96-L97


If you want to try it, download the latest artifact from here:
https://github.com/xSavior-of-God/ArmorStand-Limiter/actions/runs/2039578323
